// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wehfxrfhlokbchhbijro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlaGZ4cmZobG9rYmNoaGJpanJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Nzc4MDUsImV4cCI6MjA3MTU1MzgwNX0.LZNKUv5Y9tiQGCxonPhfYpeSfIY4hKwYkk4T88acp28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});